import { motion } from "framer-motion";
import { FileText, Download, CheckCircle2, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import GlassCard from "@/components/GlassCard";
import AnimatedCounter from "@/components/AnimatedCounter";
import { mockAnalysis, mockReportSections } from "@/services/mockData";

const fadeUp = (i: number) => ({
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0, transition: { delay: i * 0.1, duration: 0.5 } },
});

export default function Report() {
  const data = mockAnalysis;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <FileText className="w-6 h-6 text-primary" /> Executive Summary
          </h1>
          <p className="text-sm text-muted-foreground mt-1">AI-generated trade analysis report</p>
        </div>
        <Button variant="default" size="sm" onClick={() => window.print()}>
          <Download className="w-4 h-4" /> Export PDF
        </Button>
      </div>

      {/* Summary cards */}
      <motion.div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8" {...fadeUp(0)}>
        {[
          { label: "HS Code", value: data.hsCode.code, mono: true },
          { label: "Confidence", value: `${data.hsCode.confidence}%` },
          { label: "Landed Cost", value: `$${data.costBreakdown.totalLandedCost.toLocaleString()}` },
          { label: "Potential Savings", value: "$4,250" },
        ].map((card) => (
          <GlassCard key={card.label} hover className="text-center py-4">
            <p className="text-xs text-muted-foreground mb-1">{card.label}</p>
            <p className={`text-lg font-bold text-foreground ${card.mono ? "font-mono" : ""}`}>{card.value}</p>
          </GlassCard>
        ))}
      </motion.div>

      {/* Report sections */}
      <div className="space-y-6">
        {mockReportSections.map((section, i) => (
          <motion.div key={section.title} {...fadeUp(i + 1)}>
            <GlassCard hover>
              <h2 className="text-base font-semibold text-foreground mb-3">{section.title}</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-4">{section.content}</p>
              <ul className="space-y-2">
                {section.bullets.map((b, bi) => (
                  <li key={bi} className="flex items-start gap-2 text-sm">
                    <CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" />
                    <span className="text-foreground/90">{b}</span>
                  </li>
                ))}
              </ul>
            </GlassCard>
          </motion.div>
        ))}
      </div>

      {/* Disclaimer */}
      <motion.div className="mt-8" {...fadeUp(mockReportSections.length + 1)}>
        <div className="glass-card p-4 text-center">
          <p className="text-xs text-muted-foreground">
            This report was generated by Tradle AI and should be reviewed by a licensed customs broker before acting on recommendations.
          </p>
        </div>
      </motion.div>
    </div>
  );
}
